Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
        v.memory = 1014
    end

    config.vm.define "ubuntu-bionic64-expi-base" do |app|
        app.vm.box = "ubuntu/bionic64"
        app.vm.hostname = "ubuntu-base-expi"

    app.vm.synced_folder "../", "/home/expi-admin/ServerScripts"

    app.vm.provision "ansible" do |ansible|
        ansible.playbook = "../Ansible/playbook-basicsetup.yml"
    end
end
end