FROM ubuntu:bionic

RUN apt-get update && \
        apt-get install --no-install-recommends -y \
        nano \
        curl \
        git \
        apt-get autoremove \
    &&  rm -rf /var/lib/apt/lists/*